version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: contacts-agenda-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: contacts-agenda-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: contacts_agenda
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
  mongodb-data:
    driver: local
  localstack-data:
    driver: local
