spring:
  application:
    name: contacts-agenda

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/contacts_agenda}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: false

redis-cache:
  caches:
    - name: contactPages
      ttl: 5m
      cache-null-values: false

kenect:
  api:
    host: ${KENECT_API_HOST:https://candidate-challenge-api-489237493095.us-central1.run.app}
    token: ${KENECT_API_TOKEN:put-your-token-here}
    default-page-size: ${KENECT_API_DEFAULT_PAGE_SIZE:1000}

resilience4j:
  retry:
    instances:
      kenectApi:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        randomized-wait-factor: 0.5
        retry-exceptions:
          - org.springframework.web.client.RestClientException
          - java.io.IOException
          - java.util.concurrent.TimeoutException

  circuitbreaker:
    instances:
      kenectApi:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 5s
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.web.client.RestClientException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
